---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install nodejs"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "install npm"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    state: present
    global: yes
    production: yes

- name: "create directory"
  file:
    path: ~/web
    state: directory

- name: "install index page"
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: "starts the web server"
  shell: |
    pm2 start ~/web/index.js -f